#!/bin/bash

set -ex

if [[ !$RAVEDUDE_PORT ]]; then
    for d in ttyUSB0 ttyUSB1; do
        if [[ -e /dev/$d ]]; then
            export RAVEDUDE_PORT=/dev/$d
        fi
    done
fi
if [[ ! $RAVEDUDE_PORT ]]; then
    echo "Can't detect port"
    exit 1
fi

if [[ $1 == "flash" ]]; then
    shift
    cargo build --release
    ravedude nano-new -cb 57600 $@ target/avr-atmega328p/release/balance_bot_328p.elf
else
    ravedude nano-new -cb 57600 $@
fi

